/* Umbrella header for port/tools/gen_schema.py: every header that defines a
 * type reachable from archive root symbols. Hand-maintained; keep sorted. */
#include <sysdolphin/baselib/aobj.h>
#include <sysdolphin/baselib/archive.h>
#include <sysdolphin/baselib/axdriver.h>
#include <sysdolphin/baselib/axdriver.static.h>
#include <sysdolphin/baselib/bytecode.h>
#include <sysdolphin/baselib/class.h>
#include <sysdolphin/baselib/cobj.h>
#include <sysdolphin/baselib/controller.h>
#include <sysdolphin/baselib/debugconsole_main.h>
#include <sysdolphin/baselib/debug.h>
#include <sysdolphin/baselib/devcom.h>
#include <sysdolphin/baselib/devcom.static.h>
#include <sysdolphin/baselib/displayfunc.h>
#include <sysdolphin/baselib/dobj.h>
#include <sysdolphin/baselib/fobj.h>
#include <sysdolphin/baselib/fog.h>
#include <sysdolphin/baselib/forward.h>
#include <sysdolphin/baselib/generator.h>
#include <sysdolphin/baselib/gobjgxlink.h>
#include <sysdolphin/baselib/gobj.h>
#include <sysdolphin/baselib/gobjobject.h>
#include <sysdolphin/baselib/gobjplink.h>
#include <sysdolphin/baselib/gobjproc.h>
#include <sysdolphin/baselib/gobjuserdata.h>
#include <sysdolphin/baselib/hash.h>
#include <sysdolphin/baselib/hsd_3915.h>
#include <sysdolphin/baselib/hsd_3924.h>
#include <sysdolphin/baselib/hsd_392A.h>
#include <sysdolphin/baselib/hsd_392C.h>
#include <sysdolphin/baselib/hsd_3933.h>
#include <sysdolphin/baselib/hsd_393C.h>
#include <sysdolphin/baselib/hsd_397E.h>
#include <sysdolphin/baselib/hsd_3982.h>
#include <sysdolphin/baselib/hsd_3A94.h>
#include <sysdolphin/baselib/hsd_3B27.h>
#include <sysdolphin/baselib/hsd_3B2B.h>
#include <sysdolphin/baselib/hsd_3B2E.h>
#include <sysdolphin/baselib/hsd_3B33.h>
#include <sysdolphin/baselib/hsd_3B34.h>
#include <sysdolphin/baselib/id.h>
#include <sysdolphin/baselib/initialize.h>
#include <sysdolphin/baselib/jobj.h>
#include <sysdolphin/baselib/leak.h>
#include <sysdolphin/baselib/list.h>
#include <sysdolphin/baselib/lobj.h>
#include <sysdolphin/baselib/memory.h>
#include <sysdolphin/baselib/mobj.h>
#include <sysdolphin/baselib/mtx.h>
#include <sysdolphin/baselib/objalloc.h>
#include <sysdolphin/baselib/object.h>
#include <sysdolphin/baselib/particle.h>
#include <sysdolphin/baselib/particle.static.h>
#include <sysdolphin/baselib/perf.h>
#include <sysdolphin/baselib/pobj.h>
#include <sysdolphin/baselib/psappsrt.h>
#include <sysdolphin/baselib/psdisp.h>
#include <sysdolphin/baselib/psdisptev.h>
#include <sysdolphin/baselib/psstructs.h>
#include <sysdolphin/baselib/quatlib.h>
#include <sysdolphin/baselib/random.h>
#include <sysdolphin/baselib/robj.h>
#include <sysdolphin/baselib/rumble.h>
#include <sysdolphin/baselib/shadow.h>
#include <sysdolphin/baselib/sislib_font.h>
#include <sysdolphin/baselib/sislib.h>
#include <sysdolphin/baselib/sislib.static.h>
#include <sysdolphin/baselib/sobjlib.h>
#include <sysdolphin/baselib/spline.h>
#include <sysdolphin/baselib/state.h>
#include <sysdolphin/baselib/synth.h>
#include <sysdolphin/baselib/synth.static.h>
#include <sysdolphin/baselib/tev.h>
#include <sysdolphin/baselib/texpdag.h>
#include <sysdolphin/baselib/texp.h>
#include <sysdolphin/baselib/tobj.h>
#include <sysdolphin/baselib/util.h>
#include <sysdolphin/baselib/video.h>
#include <sysdolphin/baselib/wobj.h>
#include <melee/cm/types.h>
#include <melee/ef/types.h>
#include <melee/ft/types.h>
#include <melee/gm/types.h>
#include <melee/gr/types.h>
#include <melee/if/types.h>
#include <melee/it/types.h>
#include <melee/it/it_3F14.h>
#include <melee/it/itCharItems.h>
#include <melee/it/itCommonItems.h>
#include <melee/it/kinds/itdosei.h>
#include <melee/it/kinds/itkinoko.h>
#include <melee/it/kinds/itlipstickspore.h>
#include <melee/it/kinds/types.h>
#include <melee/lb/types.h>
#include <melee/mn/types.h>
#include <melee/mp/types.h>
#include <melee/pl/types.h>
#include <melee/sc/types.h>
#include <melee/ty/types.h>
#include <melee/vi/types.h>
#include <melee/ft/fighter.h>
#include <melee/sfx/crowdsfx.h>
#include <melee/ft/kinds/ftCaptain/types.h>
#include <melee/ft/kinds/ftCommon/types.h>
#include <melee/ft/kinds/ftCrazyHand/types.h>
#include <melee/ft/kinds/ftDonkey/types.h>
#include <melee/ft/kinds/ftDrMario/types.h>
#include <melee/ft/kinds/ftFox/types.h>
#include <melee/ft/kinds/ftGameWatch/types.h>
#include <melee/ft/kinds/ftKirby/types.h>
#include <melee/ft/kinds/ftKoopa/types.h>
#include <melee/ft/kinds/ftLink/types.h>
#include <melee/ft/kinds/ftLuigi/types.h>
#include <melee/ft/kinds/ftMario/types.h>
#include <melee/ft/kinds/ftMars/types.h>
#include <melee/ft/kinds/ftMasterHand/types.h>
#include <melee/ft/kinds/ftMewtwo/types.h>
#include <melee/ft/kinds/ftNess/types.h>
#include <melee/ft/kinds/ftPeach/types.h>
#include <melee/ft/kinds/ftPichu/types.h>
#include <melee/ft/kinds/ftPikachu/types.h>
#include <melee/ft/kinds/ftPopo/types.h>
#include <melee/ft/kinds/ftPurin/types.h>
#include <melee/ft/kinds/ftSamus/types.h>
#include <melee/ft/kinds/ftSandbag/types.h>
#include <melee/ft/kinds/ftSeak/types.h>
#include <melee/ft/kinds/ftYoshi/types.h>
#include <melee/ft/kinds/ftZakoBoy/types.h>
#include <melee/ft/kinds/ftZelda/types.h>
#include <melee/lb/lbanim.h>
#include "mirrors.h"
