#!/usr/bin/env bash
# port/tools/setup.sh — one-time toolchain setup for the web port.
#
# Installs emsdk (Emscripten) and clones Aurora at the pinned revision,
# applying any patches from port/extern/aurora-patches/. Safe to re-run.
set -euo pipefail

PORT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
EXTERN="$PORT_DIR/extern"
# Pinned like AURORA_REV below: "latest" means CI and a fresh clone can get a
# different compiler from the one the port is known to build with. Override in
# the environment to try a newer one.
EMSDK_VERSION="${EMSDK_VERSION:-6.0.9}"
AURORA_REPO="https://github.com/r-burns/aurora.git"
AURORA_REV="e6a6f02ace4146e8a2f648d5c274dbb7dd89665c"

mkdir -p "$EXTERN"

for tool in git cmake ninja python3; do
    command -v "$tool" >/dev/null || { echo "missing required tool: $tool" >&2; exit 1; }
done

if [ ! -d "$EXTERN/emsdk" ]; then
    git clone --depth 1 https://github.com/emscripten-core/emsdk.git "$EXTERN/emsdk"
fi
"$EXTERN/emsdk/emsdk" install "$EMSDK_VERSION"
"$EXTERN/emsdk/emsdk" activate "$EMSDK_VERSION"

if [ ! -d "$EXTERN/aurora/.git" ]; then
    git clone "$AURORA_REPO" "$EXTERN/aurora"
fi
git -C "$EXTERN/aurora" fetch -q origin
git -C "$EXTERN/aurora" checkout -q "$AURORA_REV"
git -C "$EXTERN/aurora" reset -q --hard
for p in "$PORT_DIR"/extern/aurora-patches/*.patch; do
    [ -e "$p" ] || continue
    echo "applying $(basename "$p")"
    git -C "$EXTERN/aurora" apply "$p"
done

cat > "$PORT_DIR/tools/env.sh" <<EOF
# Generated by setup.sh — source this file to put emcc on PATH.
export EMSDK_QUIET=1
source "$EXTERN/emsdk/emsdk_env.sh"
EOF

echo
echo "Setup complete. Next:"
echo "  source $PORT_DIR/tools/env.sh"
echo "  cd $PORT_DIR && cmake --preset web-debug && cmake --build --preset web-debug"
